name = "cloudflare-static-site"
main = "src/index.js"
compatibility_date = "2024-04-26"

[site]
bucket = "."
exclude = ["src", "wrangler.toml", ".git", ".github"]

[[analytics_engine_datasets]]
binding = "AGENT_TRACKER"
dataset = "agent_requests"
